name: luoyi_flutter_base
description: "my flutter base library."
version: 2.1.0
homepage: https://gitee.com/luoyi666/luoyi_flutter_base

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  mini_getx: ^5.0.0
  luoyi_dart_base: ^1.6.0
  web: ^0.5.1
  path: ^1.9.0
  path_provider: ^2.1.3
  localstorage: ^5.0.0
  flutter_hooks: ^0.20.5
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
