name: luoyi_flutter_base
description: "my flutter base library."
version: 2.4.1
homepage: https://gitee.com/luoyi666/luoyi_flutter_base

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  luoyi_dart_base: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
