name: luoyi_flutter_base
description: "my flutter base library."
version: 2.1.0
homepage: https://gitee.com/luoyi666/luoyi_flutter_base

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  mini_getx: ^5.0.7
  luoyi_dart_base: ^1.8.0
  go_router: ^14.1.4
  web: ^0.5.1
  path: ^1.9.0
  gap: ^3.0.1
  http: ^1.2.1
  path_provider: ^2.1.3
  localstorage: ^5.0.0
  flutter_hooks: ^0.20.5
  super_sliver_list: ^0.4.1
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
