name: luoyi_flutter_base
description: "my flutter base library."
version: 1.0.2
homepage: https://gitee.com/luoyi666/luoyi_flutter_base

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  luoyi_dart_base: ^1.0.0
  mini_getx: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
