name: base_example
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  luoyi_flutter_plugin:
    git:
      url: https://gitee.com/luoyi666/luoyi_flutter_plugin.git
  mini_getx: ^5.0.0
  intl: ^0.19.0
  google_fonts: ^6.2.1
  luoyi_color_picker: ^2.0.0
  collection: ^1.18.0
  localstorage: ^5.0.0
  dio: ^5.4.2
  faker: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  luoyi_flutter_base:
    path: ..

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    # 谷歌开源字体，可以商用
    - family: NotoSansSC
      fonts:
        - asset: packages/luoyi_flutter_base/fonts/NotoSansSC/NotoSansSC-Bold.ttf
        - asset: packages/luoyi_flutter_base/fonts/NotoSansSC/NotoSansSC-Medium.ttf
        - asset: packages/luoyi_flutter_base/fonts/NotoSansSC/NotoSansSC-Regular.ttf
    # 苹方字体，Apple下的设备可以商用
    - family: PingFang SC
      fonts:
        - asset: packages/luoyi_flutter_base/fonts/PingFangSC/PingFangSC-Semibold.otf
        - asset: packages/luoyi_flutter_base/fonts/PingFangSC/PingFangSC-Medium.otf
        - asset: packages/luoyi_flutter_base/fonts/PingFangSC/PingFangSC-Regular.otf
    # 小米字体，可以商用
    - family: MiSans
      fonts:
        - asset: packages/luoyi_flutter_base/fonts/MiSans/MiSans-Semibold.ttf
        - asset: packages/luoyi_flutter_base/fonts/MiSans/MiSans-Medium.ttf
    # 鸿蒙字体，可以商用
    - family: HarmonyOS Sans SC
      fonts:
        - asset: packages/luoyi_flutter_base/fonts/HarmonyOS/HarmonyOS-Bold.ttf
        - asset: packages/luoyi_flutter_base/fonts/HarmonyOS/HarmonyOS-Medium.ttf
        - asset: packages/luoyi_flutter_base/fonts/HarmonyOS/HarmonyOS-Regular.ttf

flutter_intl:
  enabled: true
