name: theme_example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_webview:
    git:
      url: https://gitee.com/luoyi666/flutter_webview
  mini_getx: ^5.0.0
  styled_widget: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  luoyi_flutter_base:
    path: ../..

flutter:
  uses-material-design: true
